### PR TITLE
Support new syntax

### PR DESCRIPTION
**Pull request by kakurasan**
This might be needed as a preparation for #167.

Depends on #165 because of `--downgrade` option.

## Syntax

```
$ truckersmp-cli (options...) [action] [game]
```

## Action names

Name|Description
---|---
`start`|Start game
`update`|Update/install latest game
`downgrade`|Downgrade game (install game from `temporary_X_Y` branch)
`updateandstart`(or `ustart`)|`update` + `start`
`downgradeandstart`(or `dstart`)|`downgrade` + `start`

## Game names

Name|Game
---|---
`ets2mp`|ETS2 multiplayer
`ets2`|ETS2 singleplayer
`atsmp`|ATS multiplayer
`ats`|ATS singleplayer

## Deprecated options

Name|Replacement
---|---
`--update`|Action (`update`, `ustart`)
`--downgrade`|Action (`downgrade`, `dstart`)
`--start`|Action (`start`, `ustart`, `dstart`)
`--singleplayer`|Game names (`ets2`, `ats`)
`--ets2`|Game names (`ets2mp`, `ets2`)
`--ats`|Game names (`atsmp`, `ats`)

### CODE REVIEW

**Comment by Lucki** [comment]
Well, I don't really see the benefit of this change but I don't have anything against it either.
AFAIK the syntax of git comes from a wrapper script (`/usr/bin/git`) that calls subscripts (`/usr/lib/git-core/commit`, `/usr/lib/git-core/status`, …) we don't really have this here.

Having options (only?) at the front seems weird. I would place them either freely or only at the end. (We also have to make sure our completions don't break here)
This is also a thing at git: Because these are different script you get different options behind `git` and `git status` - again, we don't have different scripts and can react to them at any place.

I'd like to have `ustart` and `dstart` more descriptive like proton `waitforexitandrun`.

**Comment by kakurasan** [comment]
Regarding the benefits: Easier to learn how to use, easier to use, hopefully
* I think that the current "options-only" syntax is less user-friendly than specifying "action (command) name + game name" arguments (at least for me)
* Currently users need to specify *options (not arguments)* for "basic" actions: Is this really suitable?
    * at least one of `--start` and `--update`/`--downgrade` to determine action(s)
    * one of `--ets2` and `--ats` (and `--singleplayer` optionally) to specify game

Another benefit is that users can start singleplayer game more easily (`--start {--ets2,--ats} --singleplayer` is too long).

> This is also a thing at git: Because these are different script you get different options behind `git` and `git status` - again, we don't have different scripts and can react to them at any place.

The "coming from different files" stuff is not important here. `systemctl`, `twine`, `7z`, all the commands take an argument for action (command) and I meant the syntax. `systemctl` is most similar to this PR.

> Having options (only?) at the front seems weird. I would place them either freely or only at the end.

This PR *still allows* users to do this:

```
$ truckersmp-cli start ets2mp -vv
```

However, if we use positional arguments for game options (related to #163, see https://github.com/truckersmp-cli/truckersmp-cli/pull/167#issuecomment-812582862), users would need to place options before an action:

(Note: I'm considering rebasing #167 against master after merging this PR, and the following example is using the work-in-progress branch)

```
$ truckersmp-cli start ets2mp -v -- -nointro -64bit -sysmouse
usage: truckersmp-cli [-h] [-a] [-b VERSION] [-d] [-e] [-g DIR] [-i APPID]
       ...
truckersmp-cli: error: unrecognized arguments: -- -nointro -64bit -sysmouse
```

`truckersmp-cli -v -- start ets2mp -nointro -64bit -sysmouse` or `truckersmp-cli -v start ets2mp -- -nointro -64bit -sysmouse` is ok. (I'm using Python 3.8.6.)

> I'd like to have `ustart` and `dstart` more descriptive like proton `waitforexitandrun`.

I've *added* `updateandstart` and `downgradeandstart` actions instead of replacing `ustart`/`dstart` because they're too long and I'd like to use the shorter names.

**Comment by Lucki** [comment]
Maybe it's a personal preference but placing the options before the action feels really awkward to me.
You've already tended towards `--game-options="…"` so let's go with that. We're targeting less experienced users and this PR goes towards that so we should also make the game-options as accessible as possible.

**Review by Lucki — APPROVED** [review]
Same for the readme usage examples: maybe it's personal preference but placing the options before the action feels really strange

**Comment by kakurasan** [comment]
> if we use positional arguments for game options, users would need to place options before an action
> `truckersmp-cli -v -- start ets2mp -nointro -64bit -sysmouse` or `truckersmp-cli -v start ets2mp -- -nointro -64bit -sysmouse` is ok. (I'm using Python 3.8.6.)

Actually we can also support `truckersmp-cli start ets2mp -v -- -nointro -64bit -sysmouse` by reordering options and arguments.

See my work-in-progress branch: https://github.com/kakurasan/truckersmp-cli/tree/new_syntax_custom_game_options

**Comment by Lucki** [comment]
One thing that makes you want to implement the actions is that it's more user-friendly. I can see that and I also think using `--` as delimiter will take that away again. With `--game-options="…"` it's more clear what the arguments are for. Unless it's really easy to support both we should stick with one and keep it as simple as possible.

**Review by Lucki — CHANGES_REQUESTED** [review]
The generated help text should include some more information:

~~~
positional arguments:
  {start,update,downgrade,updateandstart,ustart,downgradeandstart,dstart,none}
  {ets2mp,ets2,ats,atsmp,none}

optional arguments:
~~~

They're neither ~positional~ (actually they are to itself) nor is there any explanation and additionally this is completely missing in our generated completion files.

I'm not sure how flexible this is but I think we want something like this: https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_mutually_exclusive_group
or this: https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_argument_group

Maybe a result like this? Copied from the group example:
~~~
action:
  action description

  start     foo help
  update
  …

game:
  game description

  ets2       bar help
  ets2mp
  …

optional arguments:
~~~

**Comment by Lucki** [comment]
That's way better although the first line just includes all options instead some abbreviation.

Sadly our generated terminal completions don't properly include the new syntax.
Some options here:
* Enhance genzshcomp or
* Include static completion files

**Comment by kakurasan** [comment]
> Sadly our generated terminal completions don't properly include the new syntax.

Yes, it seems genzshcomp doesn't support positional arguments.

> Include static completion files

I guess that we can add a new script that generates them automatically (and drop genzshcomp dependency).

I'll try to do that.

**Comment by Lucki** [comment]
> I'll try to do that.

Handcrafting static files would also be totally fine, we just have to remember editing these further on.

**Comment by kakurasan** [comment]
Can this PR be merged? I implemented autogenerating bash completion and will implement zsh completion support, but I would like to *open another PR for all the completion stuff*.

**Comment by kakurasan** [comment]
Thanks. Unfortunately I guess I need more time for zsh support (due to unexpected behavior) and cannot open the PR today.

**Comment by Lucki** [comment]
> cannot open the PR today.

No need to rush, seriously, take your time.

**Pull request merged**
