### PR TITLE
Avoid using the "**" pattern

### LINKED ISSUE #345: Terminal hangs when trying to launch game
---
name: Terminal hangs when trying to launch game
about: Game not working

---

[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
Terminal hangs and nothing happens unless I press CTRL + C

## Expected behavior
Game is expected to start.

## Command
~~~
truckersmp-cli -n myusername -vv start ets2mp
~~~

## Terminal output
<details><summary>j

~~~
jonni@jonni-System-Product-Name:~$ truckersmp-cli -n myusername -vv start ets2mp
** INFO **  Platform is Linux, using Proton
** INFO **  Log file: <empty> (Default)
** INFO **  Game directory: /home/jonni/.local/share/truckersmp-cli/Euro Truck Simulator 2/data (Default)
** INFO **  Prefix directory: /home/jonni/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix (Default)
** INFO **  Game options: -nointro -64bit (Default)
** INFO **  TruckersMP MOD directory: /home/jonni/.local/share/truckersmp-cli/TruckersMP (Default)
** INFO **  Whether to disable Steam Runtime (deprecated): False (Default)
** INFO **  Whether to disable Steam Runtime: False (Default)
** INFO **  Whether to use Flatpak version of Steam: False (Default)
** INFO **  Whether to disable Steam Overlay: False (Default)
** INFO **  Proton directory: /home/jonni/.local/share/truckersmp-cli/Proton (Default)
** INFO **  Steam Runtime directory: /home/jonni/.local/share/truckersmp-cli/SteamRuntime (Default)
** INFO **  Rendering backend: gl (Default)
** INFO **  AppID/GameID: 227300 (ets2)
** DEBUG **  Updating mod files
** DEBUG **  Creating directory /home/jonni/.local/share/truckersmp-cli/TruckersMP if it doesn't exist
** DEBUG **  No files to download
** INFO **  Proton version is (major=8, minor=0)
** INFO **  Using Steam Runtime container
~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

[comment]: # (If applicable, add screenshots to help explain your problem:)

</details>

## Information
 - OS: Ubuntu 23.10
 - Proton or Wine version: Wine 6.09, Proton 8
 - truckersmp-cli version: 0.10.1

## Additional context
This started after OS re-install. Before it was working fine.

### PR DESCRIPTION
**Pull request by Lucki**
This was introduced in https://github.com/truckersmp-cli/truckersmp-cli/pull/287 and seems to be a plausible cause of #345 

@Synthron Since you seem versatile in python, may I ask you to give this a try?

fix #345

### CODE REVIEW

**Comment by Synthron** [comment]
I am actually quite new to python but I can try out the new routine and maybe find a bug or two.

my suggestion also would be to make a check whether the `--without-wine-discord-ipc-bridge` flag is used or not. If someone doesn't want to use the bridge, there is in my eyes no need to look for one in the first place

also may I suggest further debugging info in the terminal by adding to `gamestarter.py` something like
``` Python
logging.info("Looking for wine-discord-ipc-bridge. If this takes too long, try starting with the '--without-wine-discord-ipc-bridge' option.")
```

**Comment by Synthron** [comment]
came around testing it, game now starts perfectly.
Even without the `--without-wine-discord-ipc-bridge` it works, no critical errors in the logs as far as I can see

a log dump from the game start here just for completeness:

command: `truckersmp-cli start ets2mp -vv --native-steam-dir /home/marco/.steam/`

output:
```
** INFO **  Platform is Linux, using Proton
** INFO **  Log file: <empty> (Default)
** INFO **  Game directory: /home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/data (Default)
** INFO **  Prefix directory: /home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix (Default)
** INFO **  Game options: -nointro -64bit (Default)
** INFO **  TruckersMP MOD directory: /home/marco/.local/share/truckersmp-cli/TruckersMP (Default)
** INFO **  Whether to disable Steam Runtime (deprecated): False (Default)
** INFO **  Whether to disable Steam Runtime: False (Default)
** INFO **  Whether to use Flatpak version of Steam: False (Default)
** INFO **  Whether to disable Steam Overlay: False (Default)
** INFO **  Proton directory: /home/marco/.local/share/truckersmp-cli/Proton (Default)
** INFO **  Steam Runtime directory: /home/marco/.local/share/truckersmp-cli/SteamRuntime (Default)
** INFO **  Rendering backend: gl (Default)
** INFO **  AppID/GameID: 227300 (ets2)
** DEBUG **  Updating mod files
** DEBUG **  Creating directory /home/marco/.local/share/truckersmp-cli/TruckersMP if it doesn't exist
** DEBUG **  No files to download
** INFO **  Proton version is (major=8, minor=0)
** INFO **  Using Steam Runtime container
** DEBUG **  Steam is running
** INFO **  Steam installation directory: /home/marco/.steam/
** DEBUG **  Shared paths: ['/home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '/home/marco/.local/share/truckersmp-cli/Proton', '/home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix', '/home/marco/.local/share/truckersmp-cli', '/home/marco/.local/share/truckersmp-cli/TruckersMP', '/home/marco/.local/lib/python3.10/site-packages/truckersmp_cli', '/run/user/1000/discord-ipc-0', '/run/user/1000/discord-ipc-1']
** DEBUG **  Created starter for Proton
** INFO **  Starting game
** DEBUG **  Creating directory /home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix if it doesn't exist
** DEBUG **  Whether to setup native d3dcompiler_47: False
** INFO **  Running Steam Runtime helper:
  SteamAppId=227300
  SteamGameId=227300
  LD_PRELOAD=/home/marco/.steam/ubuntu12_64/gameoverlayrenderer.so
  PROTON_USE_WINED3D=0
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/marco/.steam/
  STEAM_COMPAT_DATA_PATH=/home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
  python3
    /home/marco/.local/share/truckersmp-cli/Proton/proton
    run
    /home/marco/.local/lib/python3.10/site-packages/truckersmp_cli/truckersmp-cli.exe
    /home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
    /home/marco/.local/share/truckersmp-cli/TruckersMP
      -rdevice gl -nointro -64bit
** DEBUG **  winediscordipcbridge.exe is present, MD5 is OK.
** DEBUG **  Helper arguments: ['/home/marco/.local/share/truckersmp-cli/SteamRuntime/run', '--filesystem', '/home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '--filesystem', '/home/marco/.local/share/truckersmp-cli/Proton', '--filesystem', '/home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix', '--filesystem', '/home/marco/.local/share/truckersmp-cli', '--filesystem', '/home/marco/.local/share/truckersmp-cli/TruckersMP', '--filesystem', '/home/marco/.local/lib/python3.10/site-packages/truckersmp_cli', '--filesystem', '/run/user/1000/discord-ipc-0', '--filesystem', '/run/user/1000/discord-ipc-1', '--', 'python3', '/home/marco/.local/lib/python3.10/site-packages/truckersmp_cli/steamruntime_helper.py', '--early-executable', '/home/marco/.local/share/truckersmp-cli/wine-discord-ipc-bridge/winediscordipcbridge.exe', '--early-wait-before-start', '5', '--wait-before-start', '0', '-vv', '--', 'python3', '/home/marco/.local/share/truckersmp-cli/Proton/proton', 'run', '/home/marco/.local/lib/python3.10/site-packages/truckersmp_cli/truckersmp-cli.exe', '/home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '/home/marco/.local/share/truckersmp-cli/TruckersMP', '-rdevice', 'gl', '-nointro', '-64bit']
ERROR: ld.so: object '/home/marco/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/home/marco/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/home/marco/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/home/marco/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.535.171.04 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH (unset), ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  <redacted> [API loaded no]
Executables (early): ['/home/marco/.local/share/truckersmp-cli/wine-discord-ipc-bridge/winediscordipcbridge.exe']
Executables: None
Game Arguments: ['python3', '/home/marco/.local/share/truckersmp-cli/Proton/proton', 'run', '/home/marco/.local/lib/python3.10/site-packages/truckersmp_cli/truckersmp-cli.exe', '/home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '/home/marco/.local/share/truckersmp-cli/TruckersMP', '-rdevice', 'gl', '-nointro', '-64bit']
Waiting time (early): 5
Waiting time: 0
Proton output:
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  <redacted> [API loaded no]
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-4LQEN2/${LIB}/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
not sure what causes the ld.so errors, but game starts and runs smooth

**Comment by Lucki** [comment]
> my suggestion also would be to make a check whether the `--without-wine-discord-ipc-bridge` flag is used or not. If someone doesn't want to use the bridge, there is in my eyes no need to look for one in the first place

While this looks like the easier fix, this still leaves the same problem when using the bridge.

The way I've done it should fix both use-cases, it's just a simple file finding after all.

**Comment by Synthron** [comment]
> While this looks like the easier fix, this still leaves the same problem when using the bridge.

true, but I was more referencing the fact that it is looking for something that will never be used if the flag is set. 

but with the fix it now starts repeatedly and quickly, so yay :)

**Review by kakurasan — APPROVED** [review]
It would be better to check whether `--without-wine-discord-ipc-bridge` is given (and return an empty list when disabled), but I think we should open another PR.

**Pull request merged**
