### PR TITLE
Allow to specify custom ATS/ETS2 launch options

### LINKED ISSUE #163: Adding ETS2 launch parameter
Hello,

Is it possible to add a launch option like in the Steam Game properties? In my case I need a "-sysmouse" otherwise I don't have a mouse pointer on the desktop after ALT-TAB out of the game.

### PR DESCRIPTION
**Pull request by kakurasan**
This PR adds `--game-options=` option. The specified game options are passed to ATS/ETS2.

Closes #163.

Example: `--game-options="-nointro -64bit -sysmouse"`

@Lucki Don't forget to compile `truckersmp-cli.c` and replace original `truckersmp-cli.exe` with compiled executable before testing this.

### CODE REVIEW

**Comment by Lucki** [comment]
I've seen quite often `--` as a delimiter between argument options that are handed through scripts to underlying stuff. For example the steam runtime is doing that in the other PR.

Is there any reason you did that differently, are there any pros or cons?

**Comment by kakurasan** [comment]
About the reason why I use `--` when using `run` command?

Here is an example:
```
$ LANG=C /path/to/SteamLinuxRuntime_soldier/run ls -F /
pressure-vessel-wrap[xxxxxx]: E: Unknown option -F
```

Without `--`, `-F` option is passed to `run` (`pressure-vessel-wrap`) and it fails due to unknown option.

```
$ /path/to/SteamLinuxRuntime_soldier/run -- ls -F /
bin@  etc/   lib@    lib64@      proc/  sbin@  tmp/  var/
dev/  home/  lib32@  overrides/  run/   sys/   usr/
```

With `--`, `run` doesn't use `-F` as the option for `run`.

So the answer is "because it is necessary".

**Comment by Lucki** [comment]
You misunderstood me.

I wanted to know why you decided against
~~~
truckersmp-cli [options] -- -nointro -64bit -sysmouse
~~~
in favor to
~~~
truckersmp-cli [options] --game-options="-nointro -64bit -sysmouse"
~~~

The pressure vessel example was just there to elaborate where I've seen the option delimiter used before.

**Comment by kakurasan** [comment]
> I wanted to know why you decided against ...

I simply didn't have the idea to do it like this. However, it uses positional arguments and the usage is hard to change in the future.

Actually I'm considering allowing users to start ETS2MP with `truckersmp-cli [options] start ets2mp` (like `git commit`, `ip address`, etc.), but if we use positional arguments here it would be hard.

> truckersmp-cli [options] -- -nointro -64bit -sysmouse

* Users don't need to type `--game-options=`
* Users don't need to quote options when using multiple launch options
* Users need to use `--` before options
* Developers need to change the behavior of `ArgumentParser` object
* I personally don't like to use positional arguments *only for game options* (but I think `truckersmp-cli [options] -- start ats -nointro -64bit -sysmouse` is ok)

> truckersmp-cli [options] --game-options="-nointro -64bit -sysmouse"

* Users don't need to type `--` before options
* Users need to type `--game-options=`
* Users need to quote options when using multiple launch options
* Easy to add the feature in Python script
* Positional arguments can be freely used in the future

Which do you think is better?

**Comment by Lucki** [comment]
> Which do you think is better?

> * I personally don't like to use positional arguments _only for game options_ (but I think `truckersmp-cli [options] -- start ats -nointro -64bit -sysmouse` is ok)

This looks awkward to me. So let's go with `truckersmp-cli [options] --game-options="-nointro -64bit -sysmouse"` then. That'll make it clear what gets handed to the game.

**Comment by Lucki** [comment]
Basically seems to work but I've encountered this strange thing:
~~~ sh
./truckersmp-cli start ets2mp --gamedir "/mnt/gamehub/native2proton/Euro Truck Simulator 2/" --enable-d3d11 --game-options "-64bit"
usage: truckersmp-cli [-h] [-a] [-b VERSION] [-d] [-e] [-g DIR] [-i APPID] [-l LOG] [-m DIR] [-n NAME] [-o DIR] [-p] [-s] [-u] [-v] [-w] [-x DIR] [--activate-native-d3dcompiler-47] [--check-windows-steam] [--disable-proton-overlay] [--downgrade] [--game-options OPTIONS] [--native-steam-dir DIR] [--self-update]
                      [--singleplayer] [--skip-update-proton] [--use-wined3d] [--wine-desktop SIZE] [--wine-steam-dir DIR] [--without-wine-discord-ipc-bridge] [--version]
                      [{start,update,downgrade,updateandstart,ustart,downgradeandstart,dstart,none}] [{ets2mp,ets2,ats,atsmp,none}]
truckersmp-cli: error: argument --game-options: expected one argument
~~~

These were fine:
~~~ sh
./truckersmp-cli start ets2mp […] --game-options="-64bit"
./truckersmp-cli start ets2mp […] --game-options "-64bit -nointro"
~~~

Also interesting while searching for possible parameter:
There's `-homedir "D:\profile\path"` possible which may be interesting for us to make the profile folder which contains saves and mods more accessible.

**Review by Lucki — APPROVED** [review]

**Pull request merged**
